#!/usr/bin/env node
const fs=require("fs"), path=require("path");
function pad(n){return String(n).padStart(2,"0")}
function classic(v){if(v===0)return{type:"goal",change:true,goals:1};if(v===1||v===2)return{type:"post",repeat:true};if(v===3||v===4)return{type:"crossbar",repeat:true};if(v===45)return{type:"half_time",change:true};if(v===50)return{type:"yellow",change:true,skip:1};if(v===60)return{type:"red",change:true,skip:2};if(v===90)return{type:"full_time"};if(v===96||v===97)return{type:"free_kick",special:true};if(v===98||v===99)return{type:"penalty",special:true};return{type:"miss",change:true}}
function fast(v){if(v===1||v===2)return{type:"post",repeat:true};if(v===3||v===4)return{type:"crossbar",repeat:true};if(v===50)return{type:"yellow",change:true,skip:1};if(v===60)return{type:"red",change:true,skip:2};if(v===96||v===97)return{type:"free_kick",special:true};if(v%10===9)return{type:"penalty",special:true};if(v%10===0)return{type:"goal",change:true,goals:1};return{type:"miss",change:true}}
function proc(s){let g=0;while(s.players[s.turn].skipTurns>0&&g<6){s.players[s.turn].skipTurns--;s.events.push({type:"skip",actor:s.turn});s.turn=s.turn===0?1:0;g++}}
function apply(s,v,mode){const r=mode==="fast"?fast(v):classic(v),a=s.turn,p=s.players[a];if(r.goals)p.goals+=r.goals;if(r.skip)p.skipTurns+=r.skip;if(r.change){s.turn=a===0?1:0;proc(s)}s.events.push({v,actor:a,type:r.type,turn:s.turn,skips:s.players.map(p=>p.skipTurns)});return r}
function assert(c,m,f){if(!c)f.push(m)}
let f=[],checks=[];
for(const mode of ["classic","fast"]){const cases=[{v:1,type:"post"},{v:2,type:"post"},{v:3,type:"crossbar"},{v:4,type:"crossbar"},{v:50,type:"yellow",skip:1},{v:60,type:"red",skip:2},{v:96,type:"free_kick"},{v:97,type:"free_kick"}];if(mode==="fast")cases.push({v:10,type:"goal"},{v:29,type:"penalty"},{v:90,type:"goal"});else cases.push({v:0,type:"goal"},{v:90,type:"full_time"},{v:98,type:"penalty"},{v:99,type:"penalty"});for(const c of cases){const got=mode==="fast"?fast(c.v):classic(c.v);checks.push(`${mode} ${pad(c.v)} => ${got.type}`);assert(got.type===c.type,`${mode} ${c.v}: esperado ${c.type}, obtenido ${got.type}`,f);if(c.skip)assert(got.skip===c.skip,`${mode} ${c.v}: skip esperado ${c.skip}, obtenido ${got.skip}`,f)}}
let s={turn:0,players:[{goals:0,skipTurns:0},{goals:0,skipTurns:0}],events:[]};apply(s,50,"fast");assert(s.turn===1,"Tras amarilla de P0 debe tirar P1",f);apply(s,61,"fast");assert(s.turn===1,"P0 con amarilla debe perder su siguiente turno",f);assert(s.players[0].skipTurns===0,"P0 debe consumir skip de amarilla",f);
s={turn:0,players:[{goals:0,skipTurns:0},{goals:0,skipTurns:0}],events:[]};apply(s,60,"fast");assert(s.turn===1,"Tras roja de P0 debe tirar P1",f);apply(s,61,"fast");assert(s.turn===1,"P0 con roja debe perder primer turno",f);apply(s,62,"fast");assert(s.turn===1,"P0 con roja debe perder segundo turno",f);assert(s.players[0].skipTurns===0,"P0 debe consumir los dos skips de roja",f);
const ok=f.length===0, now=new Date(), stamp=now.toISOString().replace(/[-:]/g,"").replace(/\..+/,"").replace("T","_"), dir=path.join(process.cwd(),"auditorias",stamp);fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,"auditoria_cronogol_rules.json"),JSON.stringify({ok,failures:f,checks,generatedAt:now.toISOString()},null,2));fs.writeFileSync(path.join(dir,"auditoria_cronogol_rules.md"),["# Autoauditoría CronoGol — reglas y sanciones","",`Fecha: ${now.toISOString()}`,"",`Resultado: **${ok?"OK":"FAIL"}**`,"","## Checks",...checks.map(x=>`- ${x}`),"","## Fallos",...(f.length?f.map(x=>`- ${x}`):["- Ninguno"])].join("\n"));console.log(`AUDITORIA_CRONOGOL: ${ok?"OK":"FAIL"}`);console.log(`Salida: ${dir}`);if(!ok){f.forEach(x=>console.error("- "+x));process.exit(1)}
